services:
  ranger-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ranger-admin
    entrypoint: ["/bin/bash", "/usr/local/bin/entrypoint.sh"]
    ports:
      - "6080:6080"

    volumes:
      - ranger-logs:/opt/ranger/ews/logs
    networks:
      - ranger-postgres-net
      - apache-solr_default
      - ldap_service_ldap_network
      - trino-ranger-net
    restart: "no"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6080/login.jsp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  ranger-logs:

networks:
  trino-ranger-net:
    driver: bridge
  ranger-postgres-net:
    driver: bridge
  apache-solr_default:
    external: true
  ldap_service_ldap_network:
    external: true
