services:
  ranger-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ranger-admin
    ports:
      - "6080:6080"

    volumes:
      - ranger-logs:/opt/ranger-admin/logs
    networks:
      - ranger-postgres-net
      - apache-solr_default
      - ldap_service_ldap_network
      - trino-ranger-net

volumes:
  ranger-logs:

networks:
  trino-ranger-net:
    driver: bridge
  ranger-postgres-net:
    driver: bridge
  apache-solr_default:
    external: true
  ldap_service_ldap_network:
    external: true
