services:
  ranger-admin:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ranger-admin
    ports:
      - "6080:6080"

    volumes:
      - ranger-logs:/opt/ranger-admin/logs
    networks:
      - ranger-postgres-net
    depends_on:
      ranger-db:
        condition: service_healthy
    command: ["/opt/ranger/setup.sh"]

volumes:
  ranger-logs:
  
networks:
  ranger-postgres-net:
    external: true
